# Generated by Django 5.1.9 on 2025-08-11 18:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('steps', models.JSONField(default=list, help_text='Array of step definitions')),
                ('is_active', models.BooleanField(default=True)),
                ('time_window_hours', models.IntegerField(default=24, help_text='Time window for funnel completion')),
                ('total_entries', models.IntegerField(default=0)),
                ('total_completions', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('criteria', models.JSONField(default=dict)),
                ('user_count', models.IntegerField(default=0)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('traffic_allocation', models.FloatField(default=1.0, help_text='Percentage of traffic to include in test (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('variants', models.JSONField(default=dict, help_text='Variant configurations')),
                ('primary_goal', models.CharField(blank=True, max_length=100)),
                ('secondary_goals', models.JSONField(default=list)),
                ('total_participants', models.IntegerField(default=0)),
                ('conversions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ABTestParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('converted', models.BooleanField(default=False)),
                ('conversion_goal', models.CharField(blank=True, max_length=100)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_value', models.FloatField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='analytics.abtest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['test', 'variant', 'converted'], name='analytics_a_test_id_4e0e39_idx'), models.Index(fields=['session_id', '-assigned_at'], name='analytics_a_session_53eb04_idx')],
                'unique_together': {('test', 'session_id')},
            },
        ),
        migrations.CreateModel(
            name='CustomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('properties', models.JSONField(default=dict)),
                ('value', models.FloatField(blank=True, null=True)),
                ('page_url', models.URLField(blank=True, max_length=500)),
                ('referrer_url', models.URLField(blank=True, max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['category', 'name', '-timestamp'], name='analytics_c_categor_aff468_idx'), models.Index(fields=['session_id', '-timestamp'], name='analytics_c_session_93d1e2_idx'), models.Index(fields=['-timestamp', 'processed'], name='analytics_c_timesta_4d6f82_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('entry_page', models.URLField(max_length=500)),
                ('exit_page', models.URLField(blank=True, max_length=500)),
                ('page_count', models.IntegerField(default=0)),
                ('is_bounce', models.BooleanField(default=False)),
                ('completed_goal', models.CharField(blank=True, help_text='Goal achieved during journey', max_length=100)),
                ('conversion_value', models.FloatField(blank=True, null=True)),
                ('page_path', models.JSONField(default=list)),
                ('total_events', models.IntegerField(default=0)),
                ('search_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('referrer_domain', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['session_id', '-start_time'], name='analytics_u_session_4b6c1b_idx'), models.Index(fields=['entry_page', '-start_time'], name='analytics_u_entry_p_1cdc5c_idx'), models.Index(fields=['completed_goal', '-start_time'], name='analytics_u_complet_d92b46_idx'), models.Index(fields=['-start_time', 'page_count'], name='analytics_u_start_t_3a53ec_idx')],
            },
        ),
    ]
