# Generated by Django 5.1.8 on 2025-05-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsResearchItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_item_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
