# Generated by Django 5.1.8 on 2025-05-01 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newsresearchitem_delete_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresearchitem',
            name='news_item_entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
