# Generated by Django 5.1.8 on 2025-05-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_newsresearchitem_news_item_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresearchitem',
            name='news_item_pi_first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsresearchitem',
            name='news_item_pi_last_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
