# Generated by Django 5.1.8 on 2025-05-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_newsresearchitem_news_item_pi_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresearchitem',
            name='news_item_pi_institution',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
