# Generated by Django 5.1.8 on 2025-05-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_newsresearchitem_news_item_pi_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresearchitem',
            name='news_item_pi_website',
            field=models.URLField(blank=True),
        ),
    ]
