# Generated by Django 5.1.8 on 2025-05-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_newsresearchitem_news_item_pi_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresearchitem',
            name='news_item_short_title',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
