# Generated by Django 5.1.8 on 2025-05-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_newsresearchitem_news_item_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresearchitem',
            name='news_item_blurb',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
    ]
