# Generated by Django 5.1.8 on 2025-05-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_newsresearchitem_news_item_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresearchitem',
            name='news_item_full_text',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
    ]
