# Generated by Django 5.1.8 on 2025-05-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresearchitem',
            name='news_item_full_title',
            field=models.CharField(default='Unknown', max_length=300),
            preserve_default=False,
        ),
    ]
