# Generated by Django 5.1.8 on 2025-05-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_newsresearchitem_news_item_full_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresearchitem',
            name='news_item_authors',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
    ]
