# Generated by Django 5.1.8 on 2025-05-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_newsresearchitem_news_item_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresearchitem',
            name='news_item_citation',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
    ]
