# Generated by Django 5.1.8 on 2025-05-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_newsresearchitem_news_item_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresearchitem',
            name='news_item_journal_url',
            field=models.URLField(blank=True),
        ),
    ]
