# Generated by Django 5.1.8 on 2025-05-01 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_newsresearchitem_news_item_journal_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsresearchitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='newsresearchitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
