# Generated by Django 5.1.8 on 2025-05-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_newsresearchitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsresearchitem',
            options={'ordering': ['-news_item_entry_date']},
        ),
        migrations.AlterField(
            model_name='newsresearchitem',
            name='news_item_entry_date',
            field=models.DateTimeField(),
        ),
    ]
