# Generated by Django 5.1.8 on 2025-05-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_newsresearchitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsresearchitem',
            old_name='news_item_id',
            new_name='legacy_news_id',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
