# Generated by Django 5.1.8 on 2025-05-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_news_item_id_newsresearchitem_legacy_news_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsresearchitem',
            name='legacy_news_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
