# Generated by Django 5.1.8 on 2025-05-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_newsresearchitem_legacy_news_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresearchitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
