# Generated by Django 5.1.8 on 2025-05-05 12:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_newsresearchitem_slug'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsresearchitem',
            name='slug',
        ),
        migrations.CreateModel(
            name='SponsorFeatureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurb_title', models.CharField(max_length=255)),
                ('homepage_blurb', wagtail.fields.RichTextField()),
                ('tab_one_title', models.CharField(max_length=255)),
                ('tab_one_content', wagtail.fields.RichTextField()),
                ('tab_two_title', models.CharField(max_length=255)),
                ('tab_two_content', wagtail.fields.RichTextField()),
                ('tab_three_title', models.CharField(blank=True, max_length=255)),
                ('tab_three_content', wagtail.fields.RichTextField(blank=True)),
                ('tab_four_title', models.CharField(blank=True, max_length=255)),
                ('tab_four_content', wagtail.fields.RichTextField(blank=True)),
                ('right_column_title', models.CharField(max_length=255)),
                ('right_column_content', wagtail.fields.RichTextField()),
                ('homepage_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor_home_images', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Sponsor Feature',
            },
        ),
    ]
