# Generated by Django 5.1.8 on 2025-05-05 17:26

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_newsresearchitem_slug_sponsorfeatureitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorfeatureitem',
            name='homepage_blurb',
            field=wagtail.fields.RichTextField(help_text='Use regular text here; no HTML'),
        ),
        migrations.AlterField(
            model_name='sponsorfeatureitem',
            name='right_column_content',
            field=models.TextField(help_text='This field creates the first tab — you MUST use HTML.'),
        ),
        migrations.AlterField(
            model_name='sponsorfeatureitem',
            name='tab_four_content',
            field=models.TextField(help_text='This field creates the first tab — you MUST use HTML.'),
        ),
        migrations.AlterField(
            model_name='sponsorfeatureitem',
            name='tab_one_content',
            field=models.TextField(help_text='This field creates the first tab — you MUST use HTML.'),
        ),
        migrations.AlterField(
            model_name='sponsorfeatureitem',
            name='tab_three_content',
            field=models.TextField(help_text='This field creates the first tab — you MUST use HTML.'),
        ),
        migrations.AlterField(
            model_name='sponsorfeatureitem',
            name='tab_two_content',
            field=models.TextField(help_text='This field creates the first tab — you MUST use HTML.'),
        ),
    ]
