# Generated by Django 5.1.8 on 2025-05-05 18:02

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_sponsorfeatureitem_homepage_blurb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_one_title', models.CharField(blank=True, max_length=255, null=True)),
                ('tab_one_content', wagtail.fields.RichTextField(blank=True, null=True)),
                ('tab_two_title', models.CharField(blank=True, max_length=255, null=True)),
                ('tab_two_content', wagtail.fields.RichTextField(blank=True, null=True)),
                ('tab_three_title', models.CharField(blank=True, max_length=255, null=True)),
                ('tab_three_content', wagtail.fields.RichTextField(blank=True, null=True)),
                ('tab_four_title', models.CharField(blank=True, max_length=255, null=True)),
                ('tab_four_content', wagtail.fields.RichTextField(blank=True, null=True)),
                ('right_column_content', wagtail.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sponsor Feature',
            },
        ),
        migrations.AlterModelOptions(
            name='sponsorfeatureitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='sponsorfeatureitem',
            name='right_column_content',
        ),
        migrations.RemoveField(
            model_name='sponsorfeatureitem',
            name='right_column_title',
        ),
        migrations.RemoveField(
            model_name='sponsorfeatureitem',
            name='tab_four_content',
        ),
        migrations.RemoveField(
            model_name='sponsorfeatureitem',
            name='tab_four_title',
        ),
        migrations.RemoveField(
            model_name='sponsorfeatureitem',
            name='tab_one_content',
        ),
        migrations.RemoveField(
            model_name='sponsorfeatureitem',
            name='tab_one_title',
        ),
        migrations.RemoveField(
            model_name='sponsorfeatureitem',
            name='tab_three_content',
        ),
        migrations.RemoveField(
            model_name='sponsorfeatureitem',
            name='tab_three_title',
        ),
        migrations.RemoveField(
            model_name='sponsorfeatureitem',
            name='tab_two_content',
        ),
        migrations.RemoveField(
            model_name='sponsorfeatureitem',
            name='tab_two_title',
        ),
    ]
