# Generated by Django 5.1.8 on 2025-05-06 14:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_sponsorfeature_alter_sponsorfeatureitem_options_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='SponsorFeature',
        ),
        migrations.RemoveField(
            model_name='newsresearchitem',
            name='legacy_news_id',
        ),
        migrations.AddField(
            model_name='newsresearchitem',
            name='news_item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newsresearchitem',
            name='news_item_entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='SponsorFeatureItem',
        ),
    ]
