# Generated by Django 5.1.8 on 2025-05-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_homepage_delete_sponsorfeature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresearchitem',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
