# Generated by Django 5.1.8 on 2025-05-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_newsresearchitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsresearchitem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
