# Generated by Django 5.1.8 on 2025-05-06 15:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_newsresearchitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsresearchitem',
            name='news_item_full_text',
            field=wagtail.fields.RichTextField(help_text='Full article text with HTML markup'),
        ),
    ]
