# Generated by Django 5.1.8 on 2025-05-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_newsresearchitem_news_item_full_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('President', 'President'), ('President Elect', 'President Elect'), ('Past President', 'Past President'), ('Councilor', 'Councilor'), ('Honorary', 'Honorary'), ('Obituary', 'Obituary')], max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('professional_title', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('service_start_date', models.DateField(blank=True, null=True)),
                ('service_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='newsresearchitem',
            name='news_item_full_text',
            field=models.TextField(help_text='HTML content — rendered via `|safe` in template'),
        ),
    ]
