# Generated by Django 5.1.8 on 2025-05-12 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_person_person_image'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'People Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='newsresearchitem',
            options={'ordering': ['-id'], 'verbose_name': 'News Research Item', 'verbose_name_plural': 'News Research Items'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('President', 'President'), ('President Elect', 'President Elect'), ('Immediate Past President', 'Immediate Past President'), ('Past President', 'Past President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Councilor', 'Councilor'), ('Society Manager', 'Society Manager'), ('Web Developer', 'Web Developer'), ('Honorary', 'Honorary'), ('Obituary', 'Obituary')], max_length=50),
        ),
    ]
