# Generated by Django 5.1.8 on 2025-05-14 18:04

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_committeeindexpage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obituary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obituary_id', models.IntegerField()),
                ('blurb', models.TextField(blank=True, help_text='Short HTML summary for obituary display only. Will be rendered as safe.')),
                ('full_text', models.TextField(blank=True, help_text='Full obituary content. HTML allowed. For obituary use only.')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('person', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='obituary', to='home.person', unique=True)),
            ],
            options={
                'ordering': ['-obituary_id'],
            },
        ),
    ]
