# Generated by Django 5.1.8 on 2025-05-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_obituariesindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
