# Generated by Django 5.1.8 on 2025-05-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_person_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peopleindexpage',
            options={'verbose_name': 'People Index Page'},
        ),
    ]
