# Generated by Django 5.1.8 on 2025-05-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_peopleindexpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsresearchitem',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
