# Generated by Django 5.1.8 on 2025-05-26 16:49

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_intropage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('html_body', wagtail.fields.RichTextField()),
                ('column', models.CharField(choices=[('middle', 'Middle Column'), ('right', 'Right Column')], default='middle', max_length=10)),
                ('slug', models.SlugField(help_text='Used to generate the detail page URL', unique=True)),
                ('is_lab_with_tabs', models.BooleanField(default=False)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_images', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
