# Generated by Django 5.1.8 on 2025-05-26 17:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_highlightpanel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightpanel',
            name='html_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
