# Generated by Django 5.1.8 on 2025-05-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_highlightpanel_html_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightpanel',
            name='html_body',
            field=models.TextField(blank=True, help_text='Paste HTML. Will be rendered using the `|safe` filter.'),
        ),
    ]
