# Generated by Django 5.1.8 on 2025-05-27 13:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_highlightpanel_html_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightpanel',
            name='tab1_left_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab1_right_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_tab1_images', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab1_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab2_left_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab2_right_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_tab2_images', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab2_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab3_left_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab3_right_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_tab3_images', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab3_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab4_left_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab4_right_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_tab4_images', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab4_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
