# Generated by Django 5.1.8 on 2025-05-27 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_highlightpanel_tab1_left_content_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightpanel',
            name='tab1_right_image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_tab1_images_2', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab1_right_image_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_tab1_images_3', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab1_right_image_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_tab1_images_4', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab2_right_image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_tab2_images_2', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab2_right_image_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_tab2_images_3', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab2_right_image_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_tab2_images_4', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab3_right_image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_tab3_images_2', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab3_right_image_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_tab3_images_3', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab3_right_image_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_tab3_images_4', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab4_right_image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_tab4_images_2', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab4_right_image_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_tab4_images_3', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='tab4_right_image_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlight_tab4_images_4', to='wagtailimages.image'),
        ),
    ]
