# Generated by Django 5.1.8 on 2025-05-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_highlightpanel_tab1_right_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightpanel',
            name='tab1_left_content',
            field=models.TextField(blank=True, help_text='Paste HTML. Will be rendered using the `|safe` filter.'),
        ),
        migrations.AlterField(
            model_name='highlightpanel',
            name='tab2_left_content',
            field=models.TextField(blank=True, help_text='Paste HTML. Will be rendered using the `|safe` filter.'),
        ),
        migrations.AlterField(
            model_name='highlightpanel',
            name='tab3_left_content',
            field=models.TextField(blank=True, help_text='Paste HTML. Will be rendered using the `|safe` filter.'),
        ),
        migrations.AlterField(
            model_name='highlightpanel',
            name='tab4_left_content',
            field=models.TextField(blank=True, help_text='Paste HTML. Will be rendered using the `|safe` filter.'),
        ),
    ]
