# Generated by Django 5.1.8 on 2025-05-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_highlightpanel_tab1_left_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightpanel',
            name='title',
            field=models.TextField(blank=True, help_text='Paste HTML title. Will be rendered using the `|safe` filter.'),
        ),
    ]
