# Generated by Django 5.1.8 on 2025-05-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_alter_highlightpanel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightpanel',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Uncheck to hide this panel from the homepage.'),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first in the column.'),
        ),
    ]
