# Generated by Django 5.1.9 on 2025-05-30 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_highlightpanel_is_archived_highlightpanel_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'News Item Categories',
            },
        ),
        migrations.AddField(
            model_name='newsresearchitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='home.newsitemcategory'),
        ),
    ]
