# Generated by Django 5.1.9 on 2025-05-31 16:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_newsitemcategory_newsresearchitem_category'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProceedingsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SymposiumProceeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symposium_year', models.CharField(max_length=4)),
                ('symposium_theme', models.CharField(blank=True, max_length=255)),
                ('symposium_venue', models.CharField(blank=True, max_length=255)),
                ('symposium_chair_1_name', models.CharField(blank=True, max_length=255)),
                ('symposium_chair_1_institution', models.CharField(blank=True, max_length=255)),
                ('symposium_chair_2_name', models.CharField(blank=True, max_length=255)),
                ('symposium_chair_2_institution', models.CharField(blank=True, max_length=255)),
                ('symposium_chair_3_name', models.CharField(blank=True, max_length=255)),
                ('symposium_chair_3_institution', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('program_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
        ),
    ]
