# Generated by Django 5.1.9 on 2025-07-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_highlightpanelindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightpanel',
            name='month',
            field=models.CharField(blank=True, help_text='Month this feature was published', max_length=20),
        ),
        migrations.AddField(
            model_name='highlightpanel',
            name='year',
            field=models.CharField(blank=True, help_text='Year this feature was published', max_length=4),
        ),
    ]
