# Generated by Django 5.1.9 on 2025-07-19 17:18

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_peptidelinksindexpage_researcharea_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersOnlyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for members')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('member_resources', wagtail.fields.RichTextField(blank=True, help_text='Special resources available only to members')),
            ],
            options={
                'verbose_name': 'Members-Only Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
