# Generated by Django 5.1.9 on 2025-07-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_membersonlypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresearchitem',
            name='news_item_image_caption',
            field=models.TextField(blank=True, help_text='Image caption in HTML format'),
        ),
    ]
