# Generated by Django 5.1.9 on 2025-07-28 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_add_news_image_caption'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsresearchitem',
            options={'ordering': ['-news_item_entry_date', '-id'], 'verbose_name': 'News Research Item', 'verbose_name_plural': 'News Research Items'},
        ),
        migrations.AddField(
            model_name='newsresearchitem',
            name='news_item_inline_image_1',
            field=models.ForeignKey(blank=True, help_text='First inline image - reference in text as {{image1}}', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_inline_1', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='newsresearchitem',
            name='news_item_inline_image_2',
            field=models.ForeignKey(blank=True, help_text='Second inline image - reference in text as {{image2}}', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_inline_2', to='wagtailimages.image'),
        ),
    ]
