# Generated by Django 5.1.9 on 2025-07-31 17:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_add_awards_models'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymposiumImageGalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the symposium image galleries')),
            ],
            options={
                'verbose_name': 'Symposium Image Gallery',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SymposiumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Symposium year (e.g., 2015)', max_length=4)),
                ('filename', models.CharField(help_text='Original filename without extension', max_length=255)),
                ('event_date', models.DateField(blank=True, help_text='Date when photo was taken', null=True)),
                ('caption', models.TextField(blank=True, help_text='Optional caption for the image')),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying images')),
                ('imported_from', models.CharField(blank=True, max_length=255)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('full_image', models.ForeignKey(blank=True, help_text='Full-size version of the image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symposium_full_images', to='wagtailimages.image')),
                ('thumbnail_image', models.ForeignKey(blank=True, help_text='Thumbnail version of the image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symposium_thumbnail_images', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Symposium Image',
                'verbose_name_plural': 'Symposium Images',
                'ordering': ['year', 'display_order', 'filename'],
                'indexes': [models.Index(fields=['year'], name='home_sympos_year_8a3d6c_idx'), models.Index(fields=['year', 'display_order'], name='home_sympos_year_525430_idx')],
            },
        ),
    ]
