# Generated by Django 5.1.9 on 2025-08-08 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_symposiumimagegallerypage_symposiumimage'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='member',
            field=models.OneToOneField(blank=True, help_text='Linked APS member account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researcher_profile', to='members.member'),
        ),
    ]
