# Generated by Django 5.1.9 on 2025-08-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_researcher_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='google_scholar_url',
            field=models.URLField(blank=True, help_text='Google Scholar profile or search URL'),
        ),
    ]
