# Generated by Django 5.1.9 on 2025-08-11 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_add_knowledge_base_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebasearticlepage',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='page', to='home.knowledgebasearticle'),
        ),
    ]
