# Generated by Django 5.1.9 on 2025-07-19 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDirectoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MembershipLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('annual_dues', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address_1', models.CharField(blank=True, max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('affiliation_type', models.CharField(blank=True, choices=[('academic', 'Academic'), ('industry', 'Industry'), ('government', 'Government'), ('nonprofit', 'Non-Profit'), ('student', 'Student'), ('retired', 'Retired'), ('other', 'Other')], max_length=20)),
                ('phd_year', models.IntegerField(blank=True, null=True)),
                ('research_interests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('membership_expires', models.DateField(blank=True, null=True)),
                ('data_source', models.CharField(choices=[('wordpress', 'WordPress Export'), ('legacy_only', 'Legacy Excel Only'), ('merged', 'Merged Data'), ('manual', 'Manual Entry')], default='manual', max_length=20)),
                ('import_date', models.DateTimeField(blank=True, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=50)),
                ('legacy_match_type', models.CharField(blank=True, max_length=50)),
                ('legacy_match_confidence', models.FloatField(blank=True, null=True)),
                ('wp_user_id', models.IntegerField(blank=True, null=True)),
                ('wp_user_login', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('membership_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membershiplevel')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['email'], name='members_mem_email_afed21_idx'), models.Index(fields=['status'], name='members_mem_status_734de0_idx'), models.Index(fields=['data_source'], name='members_mem_data_so_7ec1f3_idx'), models.Index(fields=['legacy_id'], name='members_mem_legacy__87fbad_idx')],
            },
        ),
    ]
