# Generated by Django 5.1.9 on 2025-08-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='directory_visible',
            field=models.BooleanField(default=True, help_text='Show this member in the public directory'),
        ),
        migrations.AddField(
            model_name='member',
            name='show_research_interests',
            field=models.BooleanField(default=True, help_text='Display research interests in directory'),
        ),
    ]
